2018-03-12 17:06:14,449 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 17, in index
    shift = (datetime.combine(datetime.today(), form.end_time.data) - datetime.combine(datetime.today(), form.start_time.data)) - datetime.combine(datetime.today(), form.break_time.data)
TypeError: unsupported operand type(s) for -: 'datetime.timedelta' and 'datetime.datetime'
2018-03-12 17:17:44,621 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 17:18:00,430 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 17:18:10,228 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 17, in index
    shift = datetime.strptime(form.end_time.data, fmt) - datetime.strptime(form.break_time.date, fmt)
TypeError: must be string, not datetime.time
2018-03-12 17:18:54,852 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 17:19:00,230 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 17, in index
    shift = datetime.strptime(str(form.end_time.data), fmt) - datetime.strptime(str(form.break_time.data), fmt)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: :00
2018-03-12 17:20:10,070 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 17:20:27,123 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 19, in index
    worked = datetime.combine(datetime.today(), shift) - datetime.combine(datetime.today(), form.start_time.data)
TypeError: combine() argument 2 must be datetime.time, not datetime.timedelta
2018-03-12 17:21:00,482 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 17:21:04,275 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 19, in index
    worked = shift - datetime.combine(datetime.today(), form.start_time.data)
TypeError: unsupported operand type(s) for -: 'datetime.timedelta' and 'datetime.datetime'
2018-03-12 17:23:56,923 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 17:24:02,321 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 19, in index
    worked = shift - form.start_time.data
TypeError: unsupported operand type(s) for -: 'datetime.timedelta' and 'datetime.time'
2018-03-12 17:31:05,019 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 17:31:11,744 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 19, in index
    start = datetime.combine(date.min, form.start_time.data) - datetime.min
NameError: global name 'date' is not defined
2018-03-12 17:31:30,763 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
