2018-03-12 16:56:46,277 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 17, in index
    shift = datetime.datetime.timedelta(form.start_time.data, form.end_time.data)
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2018-03-12 16:57:45,967 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 16:57:54,745 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 17, in index
    shift = timedelta(form.start_time.data, form.end_time.data)
NameError: global name 'timedelta' is not defined
2018-03-12 16:58:20,009 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 16:58:41,359 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 17, in index
    shift = timedelta(form.start_time.data, form.end_time.data)
TypeError: unsupported type for timedelta seconds component: datetime.time
2018-03-12 17:00:32,404 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 17:00:39,893 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 17:00:53,911 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 17, in index
    shift = form.start_time.data - form.end_time.data
TypeError: unsupported operand type(s) for -: 'datetime.time' and 'datetime.time'
2018-03-12 17:02:57,617 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 17:03:04,502 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 19, in index
    worked = shift - form.break_time.data
TypeError: unsupported operand type(s) for -: 'datetime.timedelta' and 'datetime.time'
2018-03-12 17:04:39,919 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 17:04:45,367 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 19, in index
    worked = shift - datetime.combine(datetime.today(), form.break_time.data)
TypeError: unsupported operand type(s) for -: 'datetime.timedelta' and 'datetime.datetime'
2018-03-12 17:05:22,468 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 17:05:32,534 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 17, in index
    shift = datetime.combine(datetime.today(), form.end_time.data) - datetime.combine(datetime.today(), form.start_time.data) - datetime.combine(datetime.today(), form.break_time.data)
TypeError: unsupported operand type(s) for -: 'datetime.timedelta' and 'datetime.datetime'
2018-03-12 17:06:10,172 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
