2018-03-12 15:50:59,970 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 15:51:23,178 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 15:51:40,072 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 17, in index
    worked = datetime.strptime(form.start_time.data, fmt) - datetime.strptime(form.end_time.data, fmt)
TypeError: must be string, not datetime.time
2018-03-12 15:52:29,929 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 15:52:45,774 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 17, in index
    worked = form.start_time.data - form.end_time.data - form.break_time.data
TypeError: unsupported operand type(s) for -: 'datetime.time' and 'datetime.time'
2018-03-12 15:53:52,201 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 15:54:13,413 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 17, in index
    worked = str(form.start_time.data) - str(form.end_time.data) - str(form.break_time.data)
TypeError: unsupported operand type(s) for -: 'str' and 'str'
2018-03-12 15:57:19,301 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 15:57:30,085 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 17, in index
    worked = datetime.combine(form.start_time.data, start) - datetime.combine(form.end_time.data, end) - datetime.combine(form.break_time.data, brk)
NameError: global name 'start' is not defined
2018-03-12 15:57:49,393 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 15:57:58,849 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 17, in index
    worked = datetime.combine(form.start_time.data, st) - datetime.combine(form.end_time.data, end) - datetime.combine(form.break_time.data, brk)
NameError: global name 'st' is not defined
2018-03-12 15:59:18,777 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 15:59:30,219 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 17, in index
    worked = datetime.combine(datetime.today(), form.start_time.data) - datetime.combine(datetime.today(), form.end_time.data) - datetime.combine(datetime.today(), form.break_time.data)
TypeError: unsupported operand type(s) for -: 'datetime.timedelta' and 'datetime.datetime'
2018-03-12 16:55:50,407 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
2018-03-12 16:56:01,490 ERROR: Exception on /index [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/User1/Documents/Proj/rums/app/routes.py", line 17, in index
    shift = datetime.timedelta(form.start_time.data, form.end_time.data)
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
2018-03-12 16:56:34,511 INFO: RUMS startup [in /Users/User1/Documents/Proj/rums/app/__init__.py:43]
